name = "neon-ad-spark"
compatibility_date = "2024-01-15"

[env.production]
name = "neon-ad-spark"

[env.preview]
name = "neon-ad-spark-preview"

# Pages configuration
pages_build_output_dir = "dist"

# Build configuration
[build]
command = "npm run build"
cwd = "."

# Environment variables (these will be set in Cloudflare dashboard)
# VITE_KIE_API_KEY = "your-kie-api-key"
# VITE_A4F_API_KEY = "your-a4f-api-key"

# Headers for better performance and security
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache images
[[headers]]
for = "*.jpg"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.png"
[headers.values]
Cache-Control = "public, max-age=31536000"

[[headers]]
for = "*.svg"
[headers.values]
Cache-Control = "public, max-age=31536000"

# SPA routing - redirect all routes to index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
